using Nest;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Text;

namespace BusinessLibrary.Models
{
    public class Library_card
    {

        #region Contructors

        /// <summary>
        /// Default constructor. 
        /// Need for serialization purposes.
        /// </summary>
        public Library_card()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Library_card(int id_no, string issuer_address, DateTime date_of_expiration)
        {
            Issuer_address = issuer_address;
            Id_no = id_no;
            Date_of_expiration = date_of_expiration;

        }

        /// <summary>
        /// Clone/Copy constructor.
        /// </summary>
        /// <param name="instance">The object to clone from.</param>
        public Library_card(Library_card instance)
            : this(instance.Id_no, instance.Issuer_address, instance.Date_of_expiration)
        {
        }

        #endregion

        #region Properties

        /// <summary>
        /// CardId generated by our system upon creation of a new instance.
        /// </summary>
        [JsonProperty(PropertyName = "id_no")]
        public int Id_no { get; set; }

        /// <summary>
        /// First name of the customer.
        /// </summary>
        [JsonProperty(PropertyName = "issuer_address")]
        public string Issuer_address { get; set; }

        /// <summary>
        /// Date of birth of the customer.
        /// </summary>
        [JsonProperty(PropertyName = "date_of_expiration")]
        public DateTime Date_of_expiration { get; set; }

        #endregion

        #region Methods

        /// <summary>
        /// Overrides the .ToString method.
        /// </summary>
        public override string ToString()
        {
            return "" + Id_no;
        }

        #endregion

    }
}
