using Nest;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Text;

namespace BusinessLibrary.Models
{
    public class Reccomends
    {

        #region Contructors

        /// <summary>
        /// Default constructor. 
        /// Need for serialization purposes.
        /// </summary>
        public Reccomends()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Reccomends(string reccomendation_address, int media_id, string reccomendation_card)
        {
            Reccomendation_address = reccomendation_address;
            Media_id = media_id;
            Reccomendation_card = reccomendation_card;

        }

        /// <summary>
        /// Clone/Copy constructor.
        /// </summary>
        /// <param name="instance">The object to clone from.</param>
        public Reccomends(Reccomends instance)
            : this(instance.Reccomendation_address, instance.Media_id, instance.Reccomendation_card)
        {
        }

        #endregion

        #region Properties

        /// <summary>
        /// CardId generated by our system upon creation of a new instance.
        /// </summary>
        [JsonProperty(PropertyName = "reccomendation_address")]
        public string Reccomendation_address { get; set; }

        /// <summary>
        /// First name of the customer.
        /// </summary>
        [JsonProperty(PropertyName = "media_id")]
        public int Media_id { get; set; }

        /// <summary>
        /// Last name of the customer.
        /// </summary>
        [JsonProperty(PropertyName = "reccomendation_card")]
        public string Reccomendation_card { get; set; }

        #endregion

        #region Methods

        /// <summary>
        /// Overrides the .ToString method.
        /// </summary>
        public override string ToString()
        {
            return "" + Media_id;
        }

        #endregion

    }
}
