using Nest;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Text;

namespace BusinessLibrary.Models
{
    public class Recommends
    {

        #region Contructors

        /// <summary>
        /// Default constructor. 
        /// Need for serialization purposes.
        /// </summary>
        public Recommends()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Recommends(string recommendation_address, int media_id, string recommendation_card)
        {
            Recommendation_address = recommendation_address;
            Media_id = media_id;
            Recommendation_card = recommendation_card;

        }

        /// <summary>
        /// Clone/Copy constructor.
        /// </summary>
        /// <param name="instance">The object to clone from.</param>
        public Recommends(Recommends instance)
            : this(instance.Recommendation_address, instance.Media_id, instance.Recommendation_card)
        {
        }

        #endregion

        #region Properties

        /// <summary>
        /// CardId generated by our system upon creation of a new instance.
        /// </summary>
        [JsonProperty(PropertyName = "recommendation_address")]
        public string Recommendation_address { get; set; }

        /// <summary>
        /// First name of the customer.
        /// </summary>
        [JsonProperty(PropertyName = "media_id")]
        public int Media_id { get; set; }

        /// <summary>
        /// Last name of the customer.
        /// </summary>
        [JsonProperty(PropertyName = "recommendation_card")]
        public string Recommendation_card { get; set; }

        #endregion

        #region Methods

        /// <summary>
        /// Overrides the .ToString method.
        /// </summary>
        public override string ToString()
        {
            return "" + Media_id;
        }

        #endregion

    }
}
