using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseLibrary.Models
{
    public class Author_db
    {

        #region Constructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        public Author_db()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Author_db(string author_id, string firstName, string lastName, DateTime dateOfBirth)
        {
            Author_id = author_id;
            First_name = firstName;
            Last_name = lastName;
            Date_of_birth = dateOfBirth;
        }

        #endregion

        #region Properties

        /// <summary>
        /// CardId generated by our system upon creation of a new instance.
        /// </summary>
        public string Author_id { get; set; }

        /// <summary>
        /// First name used of the customer.
        /// </summary>
        public string First_name { get; set; }

        /// <summary>
        /// Last name used of the customer.
        /// </summary>
        public string Last_name { get; set; }

        /// <summary>
        /// Date of birth used of the customer.
        /// </summary>
        public DateTime Date_of_birth { get; set; }
        #endregion

    }
}
