using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseLibrary.Models
{
    public class Customer_db
    {

        #region Constructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        public Customer_db()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Customer_db(int cardId, string firstName, string lastName, string password, string address, DateTime dateOfBirth)
        {
            Card_id = cardId;
            First_name = firstName;
            Last_name = lastName;
            Password = password;
            Address = address;
            Date_of_birth = dateOfBirth;
        }

        #endregion

        #region Properties

        /// <summary>
        /// CardId generated by our system upon creation of a new instance.
        /// </summary>
        public int Card_id { get; set; }

        /// <summary>
        /// First name used of the customer.
        /// </summary>
        public string First_name { get; set; }

        /// <summary>
        /// Last name used of the customer.
        /// </summary>
        public string Last_name { get; set; }

        /// <summary>
        /// Password used of the customer.
        /// </summary>
        public string Password { get; set; }

        /// <summary>
        /// Address used of the customer.
        /// </summary>
        public string Address { get; set; }

        /// <summary>
        /// Date of birth used of the customer.
        /// </summary>
        public DateTime Date_of_birth { get; set; }
        #endregion

    }
}
