using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseLibrary.Models
{
    public class Library_db
    {

        #region Constructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        public Library_db()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Library_db(string address, string name, string website_address, string admin_id)
        {
            Address = address;
            Name = name;
            Website_address = website_address;
            Admin_id = admin_id;
        }

        #endregion

        #region Properties

        /// <summary>
        /// CardId generated by our system upon creation of a new instance.
        /// </summary>
        public string Address { get; set; }

        /// <summary>
        /// First name used of the customer.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Last name used of the customer.
        /// </summary>
        public string Website_address { get; set; }

        /// <summary>
        /// Password used of the customer.
        /// </summary>
        public string Admin_id { get; set; }
        #endregion

    }
}
