using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseLibrary.Models
{
    public class Library_card_db
    {

        #region Constructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        public Library_card_db()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Library_card_db(int id_no, string issuer_address, DateTime date_of_expiration)
        {
            Issuer_address = issuer_address;
            Id_no = id_no;
            Date_of_expiration = date_of_expiration;
        }

        #endregion

        #region Properties

        /// <summary>
        /// CardId generated by our system upon creation of a new instance.
        /// </summary>
        public int Id_no { get; set; }

        /// <summary>
        /// First name used of the customer.
        /// </summary>
        public string Issuer_address { get; set; }

        /// <summary>
        /// Date of birth used of the customer.
        /// </summary>
        public DateTime Date_of_expiration { get; set; }
        #endregion

    }
}
