using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseLibrary.Models
{
    public class Librarian_db
    {

        #region Constructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        public Librarian_db()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Librarian_db(string employee_id, string firstName, string lastName, string phone_no, string address, string social_insurance_no, string library_address)
        {
            Employee_id = employee_id;
            First_name = firstName;
            Last_name = lastName;
            Phone_no = phone_no;
            Address = address;
            Social_insurance_no = social_insurance_no;
            Library_address = library_address;
        }

        #endregion

        #region Properties

        /// <summary>
        /// Employee id generated by our system upon creation of a new instance.
        /// </summary>
        public string Employee_id { get; set; }

        /// <summary>
        /// First name of the librarian.
        /// </summary>
        public string First_name { get; set; }

        /// <summary>
        /// Last name of the librarian.
        /// </summary>
        public string Last_name { get; set; }

        /// <summary>
        /// Phone number of the librarian.
        /// </summary>
        public string Phone_no { get; set; }

        /// <summary>
        /// Address of the librarian.
        /// </summary>
        public string Address { get; set; }

        /// <summary>
        /// Social security number of librarian.
        /// </summary>
        public string Social_insurance_no { get; set; }

        /// <summary>
        /// Library that librarian works at.
        /// </summary>
        public string Library_address { get; set; }
        #endregion

    }
}
